from selenium import webdriver
import time
from selenium.webdriver.support.select import Select

if __name__ == '__main__':
    driver = webdriver.Chrome('../chromedriver/chromedriver.exe')
    driver.get("http://192.168.60.146:8080/demo1.html")
    time.sleep(1)
    input_el = driver.find_element_by_xpath('/html/body/table/tbody/tr[2]/td[2]/input')
    input_el.send_keys('只要E的够快,队友问号就追不上你')
    time.sleep(1)
    input_el.clear()
    time.sleep(1)
    file_el = driver.find_element_by_id('file1')
    file_el.send_keys('C:/Users/Administrator/Desktop/1560155219(1).jpg')
    time.sleep(1)
    radio_els = driver.find_elements_by_name('radio')
    print(type(radio_els))
    radio_els[0].click()
    time.sleep(1)
    radio_els[1].click()
    time.sleep(1)
    checkbox_els = driver.find_elements_by_class_name('checkbox')
    print(checkbox_els)
    checkbox_els[0].click()
    time.sleep(1)
    checkbox_els[1].click()
    time.sleep(1)
    checkbox_els[2].click()
    time.sleep(1)
    button_el = driver.find_element_by_xpath('//input[@value="普通按钮"]')
    button_el.click()
    time.sleep(1)
    driver.switch_to.alert.send_keys('我不知道说啥')
    time.sleep(1)
    driver.switch_to.alert.accept()
    time.sleep(1)
    driver.find_element_by_xpath('//input[@type="password"]').send_keys('132456')
    number_el = driver.find_element_by_xpath('//input[@type="number"]')
    number_el.send_keys('20')
    time.sleep(1)
    driver.find_element_by_xpath('//textarea').send_keys('只要E的够快,队友的问号就追不上你')
    time.sleep(1)
    selector_el = driver.find_element_by_css_selector('body > table > tbody > tr:nth-child(12) > td:nth-child(2) > select')
    s = Select(selector_el)
    s.select_by_index(1)
    time.sleep(1)
    s.select_by_value('z1')
    time.sleep(1)
    s.select_by_visible_text('周龙3')
    time.sleep(1)
    driver.find_element_by_link_text('当当').click()
    time.sleep(3)
    driver.back()
    time.sleep(1)
    driver.find_element_by_partial_link_text('度娘').click()
    time.sleep(3)
    driver.back()
    time.sleep(1)
    driver.forward()
    time.sleep(3)
    driver.refresh()
    time.sleep(3)
    driver.quit()



    




